# Wordlists for the bot to check for
# More obscure words are at the bottom (seperated by a newline)
good_words = set([
<<<<<<< HEAD
  'beautiful', 'attractive', 'sexy', 'good', 'pog', 'cool', 'nice',
  'legendary', 'great', 'neat', 'best', 'brilliant', 'incredible ',
  'fantastic', 'godly', 'lovely', 'pretty', 'perfect', 'neat', 'smart',
  'super', 'sweet', 'wholesome', 'wise', 'swag', 'poggers', 'clever',
  'conscious', 'cute', 'funny', 'fun', 'friendly', 'flattering', 'glorious',
  'helpful', 'inspiring', 'intelligent', 'kind', 'marvellous', 'pleasant',
  'polite', 'perceptive', 'patient', 'praiseworthy', 'rational', 'self aware',
  'sensational', 'sensible', 'sharp', 'strong', 'spectacular', 'stunning',
  'superior', 'supportive', 'thoughtful', 'trustworthy', 'unparalleled',
  'valuable', 'vigilant', 'well mannered', 'wonderful', 'captivating',
  'magnificent', 'breathtaking', 'splendid', 'stellar', 'epic', 'sigma',
=======
  'beautiful',
  'attractive',
  'sexy',
  'good',
  'pog',
  'cool',
  'nice',
  'legendary',
  'great',
  'neat',
  'best',
  'brilliant',
  'incredible ',
  'fantastic',
  'godly',
  'lovely',
  'pretty',
  'perfect',
  'neat',
  'smart',
  'super',
  'sweet',
  'wholesome',
  'wise',
  'swag',
  'poggers',
  'clever',
  'conscious',
  'cute',
  'funny',
  'fun',
  'friendly',
  'flattering',
  'glorious',
  'helpful',
  'inspiring',
  'intelligent',
  'kind',
  'marvellous',
  'pleasant',
  'polite',
  'perceptive',
  'patient',
  'praiseworthy',
  'rational',
  'self aware',
  'sensational',
  'sensible',
  'sharp',
  'strong',
  'spectacular',
  'stunning',
  'superior',
  'supportive',
  'thoughtful',
  'trustworthy',
  'unparalleled',
  'valuable',
  'vigilant',
  'well mannered',
  'wonderful',
  'captivating',
  'magnificent',
  'breathtaking',
  'splendid',
  'stellar',
  'epic',
  'sigma',
  'alpha'
])

neutral_words = set(['special', 'drunk', 'faulty', 'confusing', 'goofy ahh'])

bad_words = set([
  'bad', 'stupid', 'mean', 'dumb', 'cringe', 'weird', 'rude', 'lazy',
  'foolish', 'cruel', 'awful', 'idiot', 'ugly', 'basic', 'bland', 'bizare',
  'bloated', 'blind', 'bloody', 'blunt', 'boring', 'brainless', 'cancerous',
  'mentally challenged', 'cheap', 'childish', 'clueless', 'cocky',
  'concerning', 'convoluted', 'corny', 'corrupt', 'cowardly', 'costly',
  'crazy', 'daft', 'dangerous', 'defective', 'deformed', 'dense', 'dirty',
  'disgusting', 'empty', 'faulty', 'idiotic', 'moody', 'nosy', 'petty',
  'pitiful', 'tacky', 'ballsucking', 'imbecile', 'crybaby', 'no bitches', 'baby'
])

evil_words = set([
  'coldhearted', 'cruel', 'controversial', 'creepy', 'evil', 'racist', 'toxic',
  'sexist', 'sex offender', 'maleficent', 'despicable', 'morally challenged'
])

aussie_words = set(['mate', 'bloke', 'crikey', 'wombat', 'chur'])
